# Generated by Django 3.1 on 2020-08-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_assistant_student_teacher_user'),
    ]

    operations = [
    ]
