# Generated by Django 3.1 on 2020-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200815_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.CharField(default='', max_length=128),
        ),
    ]
